#!/usr/bin/env bash
# Vendor AceEngineer's marine-offshore skill corpus into the ace-marine-dynamics
# plugin, recording provenance so a rebuild is verifiable.
#
#   ./scripts/sync-skills.sh            vendor (overwrites the plugin skills/ tree)
#   ./scripts/sync-skills.sh --verify   rebuild into a temp dir and assert byte-identical
#
# Source of truth is workspace-hub. Never hand-edit the vendored copies — edit
# upstream and re-run this, or the provenance manifest becomes a lie.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_REPO="${ACE_SKILLS_SRC:-$REPO_ROOT/../workspace-hub}"
SRC="$SRC_REPO/.claude/skills/engineering/marine-offshore"
DEST="$REPO_ROOT/plugins/ace-marine-dynamics/skills"
MANIFEST="$REPO_ROOT/plugins/ace-marine-dynamics/SKILLS-PROVENANCE.md"

[ -d "$SRC" ] || { echo "FATAL: source not found: $SRC" >&2; exit 1; }

vendor_into() {
  local out="$1"
  mkdir -p "$out"
  # Skills only: SKILL.md plus its supporting files. No archives, no VCS metadata.
  ( cd "$SRC" && find . -type f \
      ! -path "./_archive/*" ! -name ".DS_Store" ! -name "*.alias" -print0 ) \
    | ( cd "$SRC" && tar --null -cf - --files-from=- ) \
    | ( cd "$out" && tar -xf - )
}

tree_hash() {
  ( cd "$1" && find . -type f | LC_ALL=C sort | xargs shasum -a 256 | shasum -a 256 | cut -d' ' -f1 )
}

if [ "${1:-}" = "--verify" ]; then
  [ -d "$DEST" ] || { echo "FAIL: nothing vendored yet at $DEST" >&2; exit 1; }
  TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
  vendor_into "$TMP"
  if diff -r "$DEST" "$TMP" >/dev/null 2>&1; then
    echo "VERIFY PASS: vendored tree is byte-identical to a fresh build from $SRC"
    echo "  tree sha256: $(tree_hash "$DEST")"
    exit 0
  fi
  echo "VERIFY FAIL: vendored tree differs from a fresh build" >&2
  diff -r "$DEST" "$TMP" >&2 || true
  exit 1
fi

rm -rf "$DEST"
vendor_into "$DEST"

SRC_SHA="$(git -C "$SRC_REPO" rev-parse HEAD 2>/dev/null || echo UNKNOWN)"
SRC_DIRTY="$(git -C "$SRC_REPO" status --porcelain 2>/dev/null | wc -l | tr -d ' ')"
COUNT="$(find "$DEST" -name SKILL.md | wc -l | tr -d ' ')"

cat > "$MANIFEST" <<EOF
# Skills provenance — ace-marine-dynamics

Generated by \`scripts/sync-skills.sh\`. Do not hand-edit the vendored \`skills/\`
tree; edit upstream and re-run.

| Field | Value |
|---|---|
| Source repo | \`$(git -C "$SRC_REPO" remote get-url origin 2>/dev/null || echo "$SRC_REPO")\` |
| Source path | \`.claude/skills/engineering/marine-offshore\` |
| Source commit | \`$SRC_SHA\` |
| Uncommitted files at sync time | $SRC_DIRTY |
| SKILL.md count | $COUNT |
| Tree sha256 | \`$(tree_hash "$DEST")\` |
| Synced (UTC) | $(date -u +%Y-%m-%dT%H:%M:%SZ) |

Verify a rebuild is byte-identical:

\`\`\`bash
./scripts/sync-skills.sh --verify
\`\`\`
EOF

echo "Vendored $COUNT skills -> $DEST"
echo "Provenance -> $MANIFEST"
